services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/taxi-service
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
